### pandas模块：
可以基于该模块进行excel表格的数据处理

In [6]:
#pip install pandas
import pandas as pd

In [7]:
#1.读取加载Excel文件数据
data = pd.read_excel('篮球赛.xlsx',sheet_name='aaa')
data

     对手 胜负  主客场    命中  投篮数  投篮命中率  3分命中率    篮板  助攻    得分
0    勇士  胜    客  10.0   23  0.435  0.444   6.0  11  27.0
1    国王  胜    客   8.0   21  0.381  0.286   3.0   9  27.0
2    小牛  胜    主  10.0   19  0.526  0.462   3.0   7  29.0
3    灰熊  负    主   8.0   20  0.400  0.250   5.0   8  22.0
4   76人  胜    客   NaN   20    NaN  0.250   NaN  13   NaN
5    黄蜂  胜    客   8.0   18  0.444  0.400  10.0  11  27.0
6    灰熊  负    客   6.0   19  0.316  0.222   4.0   8  20.0
7   76人  负    主   8.0   21  0.381  0.429   4.0   7  29.0
8   尼克斯  胜  NaN   9.0   23  0.391  0.353   5.0   9  31.0
9    老鹰  胜    客   8.0   15  0.533  0.545   3.0  11  29.0
10   爵士  胜    主  19.0   25  0.760  0.875   2.0  13  56.0
11   骑士  胜    主   8.0   21    NaN  0.429  11.0  13  35.0
12   灰熊  胜    主  11.0   25  0.440  0.429   4.0   8  38.0
13  步行者  胜    客   9.0   21  0.429  0.250   5.0  15  26.0
14   猛龙  负    主   8.0   25  0.320  0.273   6.0  11  38.0
15   太阳  胜    客  12.0   22  0.545  0.545   2.0   7  48.0
16   灰熊  胜    客   9.0   20  0.450  0.500   5.0   7  29.0
17   掘金  胜    主   6.0   16  0.375  0.143   8.0   9  21.0
18  尼克斯  胜    主  12.0   27  0.444  0.385   2.0  10  37.0
19   篮网  胜    主  13.0   20  0.650  0.615  10.0   8  37.0
20  步行者  胜    主   8.0   22  0.364  0.333   8.0  10  29.0
21   湖人  胜    客  13.0   22  0.591  0.444   4.0   9  36.0
22   爵士  胜    客   8.0   19  0.421  0.333   5.0   3  29.0
23  开拓者  胜    客  16.0   29  0.552  0.571   8.0   3  48.0
24   鹈鹕  胜    主   8.0   16  0.500  0.400   1.0  17  26.0
25   灰熊  胜    主  11.0   25  0.440  0.429   4.0   8  38.0
26   灰熊  胜    主  11.0   25  0.440  0.429   4.0   8  38.0
27   灰熊  胜    主  11.0   25  0.440  0.429   4.0   8  38.0

In [8]:
#2.查看数据表格的形状
data.shape  #数据表格有28行10列

(28, 10)

In [10]:
#3.数据去重
data['胜负'].unique() #将data数据表格中胜负这一列的数据取出，调用了unique函数（数据去重）

array(['胜', '负'], dtype=object)

In [11]:
#4.统计元素出现的个数
data['胜负'].value_counts() #统计胜负列中每个元素出现的次数

胜负
胜    24
负     4
Name: count, dtype: int64

In [12]:
#5.检测数据中是否有重复的行数据
data.duplicated() #duplicated函数会针对data的每一行进行重复检测，如果发现某行重复了就给改行返回一个True，否则返回一个False

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27     True
dtype: bool

In [13]:
data.duplicated().sum() #统计重复行的个数

np.int64(3)

In [18]:
#6.删除重复的行数据
data.drop_duplicates()

     对手 胜负  主客场    命中  投篮数  投篮命中率  3分命中率    篮板  助攻    得分
0    勇士  胜    客  10.0   23  0.435  0.444   6.0  11  27.0
1    国王  胜    客   8.0   21  0.381  0.286   3.0   9  27.0
2    小牛  胜    主  10.0   19  0.526  0.462   3.0   7  29.0
3    灰熊  负    主   8.0   20  0.400  0.250   5.0   8  22.0
4   76人  胜    客   NaN   20    NaN  0.250   NaN  13   NaN
5    黄蜂  胜    客   8.0   18  0.444  0.400  10.0  11  27.0
6    灰熊  负    客   6.0   19  0.316  0.222   4.0   8  20.0
7   76人  负    主   8.0   21  0.381  0.429   4.0   7  29.0
8   尼克斯  胜  NaN   9.0   23  0.391  0.353   5.0   9  31.0
9    老鹰  胜    客   8.0   15  0.533  0.545   3.0  11  29.0
10   爵士  胜    主  19.0   25  0.760  0.875   2.0  13  56.0
11   骑士  胜    主   8.0   21    NaN  0.429  11.0  13  35.0
12   灰熊  胜    主  11.0   25  0.440  0.429   4.0   8  38.0
13  步行者  胜    客   9.0   21  0.429  0.250   5.0  15  26.0
14   猛龙  负    主   8.0   25  0.320  0.273   6.0  11  38.0
15   太阳  胜    客  12.0   22  0.545  0.545   2.0   7  48.0
16   灰熊  胜    客   9.0   20  0.450  0.500   5.0   7  29.0
17   掘金  胜    主   6.0   16  0.375  0.143   8.0   9  21.0
18  尼克斯  胜    主  12.0   27  0.444  0.385   2.0  10  37.0
19   篮网  胜    主  13.0   20  0.650  0.615  10.0   8  37.0
20  步行者  胜    主   8.0   22  0.364  0.333   8.0  10  29.0
21   湖人  胜    客  13.0   22  0.591  0.444   4.0   9  36.0
22   爵士  胜    客   8.0   19  0.421  0.333   5.0   3  29.0
23  开拓者  胜    客  16.0   29  0.552  0.571   8.0   3  48.0
24   鹈鹕  胜    主   8.0   16  0.500  0.400   1.0  17  26.0

In [16]:
#7.删除空值对应的行数据
data.dropna()

     对手 胜负 主客场    命中  投篮数  投篮命中率  3分命中率    篮板  助攻    得分
0    勇士  胜   客  10.0   23  0.435  0.444   6.0  11  27.0
1    国王  胜   客   8.0   21  0.381  0.286   3.0   9  27.0
2    小牛  胜   主  10.0   19  0.526  0.462   3.0   7  29.0
3    灰熊  负   主   8.0   20  0.400  0.250   5.0   8  22.0
5    黄蜂  胜   客   8.0   18  0.444  0.400  10.0  11  27.0
6    灰熊  负   客   6.0   19  0.316  0.222   4.0   8  20.0
7   76人  负   主   8.0   21  0.381  0.429   4.0   7  29.0
9    老鹰  胜   客   8.0   15  0.533  0.545   3.0  11  29.0
10   爵士  胜   主  19.0   25  0.760  0.875   2.0  13  56.0
12   灰熊  胜   主  11.0   25  0.440  0.429   4.0   8  38.0
13  步行者  胜   客   9.0   21  0.429  0.250   5.0  15  26.0
14   猛龙  负   主   8.0   25  0.320  0.273   6.0  11  38.0
15   太阳  胜   客  12.0   22  0.545  0.545   2.0   7  48.0
16   灰熊  胜   客   9.0   20  0.450  0.500   5.0   7  29.0
17   掘金  胜   主   6.0   16  0.375  0.143   8.0   9  21.0
18  尼克斯  胜   主  12.0   27  0.444  0.385   2.0  10  37.0
19   篮网  胜   主  13.0   20  0.650  0.615  10.0   8  37.0
20  步行者  胜   主   8.0   22  0.364  0.333   8.0  10  29.0
21   湖人  胜   客  13.0   22  0.591  0.444   4.0   9  36.0
22   爵士  胜   客   8.0   19  0.421  0.333   5.0   3  29.0
23  开拓者  胜   客  16.0   29  0.552  0.571   8.0   3  48.0
24   鹈鹕  胜   主   8.0   16  0.500  0.400   1.0  17  26.0
25   灰熊  胜   主  11.0   25  0.440  0.429   4.0   8  38.0
26   灰熊  胜   主  11.0   25  0.440  0.429   4.0   8  38.0
27   灰熊  胜   主  11.0   25  0.440  0.429   4.0   8  38.0

In [20]:
#8.可以将处理后的数据写回到Excel文件中保存
data.to_excel('./ret.xlsx')

In [22]:
data.head(3)

   对手 胜负 主客场    命中  投篮数  投篮命中率  3分命中率   篮板  助攻    得分
0  勇士  胜   客  10.0   23  0.435  0.444  6.0  11  27.0
1  国王  胜   客   8.0   21  0.381  0.286  3.0   9  27.0
2  小牛  胜   主  10.0   19  0.526  0.462  3.0   7  29.0

In [23]:
exec("print('hello world')")

hello world

In [24]:
print('hello world')

hello world

In [ ]:
#数据合并
pd.merge()